### ISSUE TITLE
Deleting an organism does not remove it from the menu

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/tripal_manage_menus#11]
See the hardwoodgenomics.org Trees menu. Look for Juglans nigra (Genome). If you click on that link it takes you to a 404. 

@jwest60 how can we fix this?

**Comment by jwest60** [comment]
hmmmm the juglans nigra page seems to be working for me

https://www.hardwoodgenomics.org/organism/Juglans/nigra

im not sure why it wouldnt be deleting the organism from the menu if the organism is deleted from the site, theres code for it and i just tested it on my dev site and it seems to be working. is the module updated to the latest version on the live site?

**Comment by almasaeed2010** [comment]
There are 2 Jugluns nigras. The broken one has `(Genome)` in its name.

**Comment by almasaeed2010** [comment]
The module is at latest master.

**Comment by almasaeed2010** [comment]
Never mind, a cache issue.
