### ISSUE TITLE
module causes warnings on creating new bundle type

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_manage_menus#6]
```
Notice: Undefined property: TripalTerm::$term_id in tripal_manage_menus_entity_insert() (line 21 of /Users/chet/UTK/tripal/sites/all/modules/custom/tripal_manage_menus/tripal_manage_menus.module).
```

the hook probably needs to check first to make sure its the right thing (an organism) and exit if not...

**Comment by jwest60** [comment]
@bradfordcondon the hook actually does check to see if the entity is an organism first
```
function tripal_manage_menus_entity_insert($entity, $type) {
  if (in_array($entity->term_id, tripal_manage_menus_get_entity_bundle('organism')))
    tripal_manage_menus_rebuild_menu_links('main-menu', 'Trees', 'organism');
}
```
any idea why it's not working?

**Comment by bradfordcondon** [comment]
the error is ` Undefined property: TripalTerm::$term_id `  so you need to first check that the key "termi_id" exists in the object $entity.  http://php.net/manual/en/function.property-exists.php

```
 if (property_exists( $entity, "term_id") && in_array($entity->term_id, tripal_manage_menus_get_entity_bundle('organism')))
```

**Comment by jwest60** [comment]
@bradfordcondon should be fixed now, give it a try when you get a chance

**Comment by bradfordcondon** [comment]
resolved!  Thanks @jwest60
