### ISSUE TITLE
Duplicate organisms get deleted

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/tripal_manage_menus#7]
When we delete an organism entity that is a duplicate (ie has the same genus and species), all instances are deleted from the menu. We need away to delete the menu item simply using the entity ID rather than the genus/species if possible.

@jwest60 I am assigning you this issue but if you need help please let me know.

**Comment by jwest60** [comment]
the menu link has no knowledge of the organism other than its name and where it exists on the site, but i think that the id can be generated from the menu link

**Comment by jwest60** [comment]
fixed
